// src/components/CTA.tsx
import React from "react";
import { ArrowRight, CheckCircle } from "lucide-react";
import { motion } from "motion/react";

export function CTA() {
  const benefits = [
    "Acceso anticipado disponible próximamente",
    "Implementación y capacitación incluidas",
    "Soporte técnico especializado",
    "Migración de datos sin costo",
  ];

  return (
    <section id="contacto" className="py-16 md:py-24 px-4 bg-background">
      <div className="max-w-5xl mx-auto">
        <motion.div
          className="bg-gradient-to-br from-primary via-secondary to-primary rounded-3xl p-8 md:p-12 lg:p-16 shadow-2xl relative overflow-hidden"
          initial={{ opacity: 0, scale: 0.9 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
        >
          {/* Decorative elements */}
          <motion.div
            className="absolute top-0 right-0 w-64 h-64 bg-primary-foreground/10 rounded-full blur-3xl"
            animate={{
              scale: [1, 1.2, 1],
              opacity: [0.1, 0.2, 0.1],
            }}
            transition={{
              duration: 8,
              repeat: Infinity,
              ease: "easeInOut",
            }}
          ></motion.div>
          <motion.div
            className="absolute bottom-0 left-0 w-48 h-48 bg-primary-foreground/10 rounded-full blur-3xl"
            animate={{
              scale: [1, 1.3, 1],
              opacity: [0.1, 0.15, 0.1],
            }}
            transition={{
              duration: 6,
              repeat: Infinity,
              ease: "easeInOut",
            }}
          ></motion.div>

          <div className="relative z-10 text-center space-y-6">
            <motion.h2
              className="text-3xl md:text-4xl lg:text-5xl text-primary-foreground"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.2, duration: 0.6 }}
            >
              ¿Listo para modernizar tu práctica médica?
            </motion.h2>

            <motion.p
              className="text-primary-foreground/90 text-lg max-w-2xl mx-auto"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.3, duration: 0.6 }}
            >
              Únete a más de 150 clínicas y 2,000 profesionales de la salud que
              confían en EveryMed
            </motion.p>

            {/* Benefits */}
            <motion.div
              className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-3xl mx-auto py-6"
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              transition={{ delay: 0.4, duration: 0.6 }}
            >
              {benefits.map((benefit, index) => (
                <motion.div
                  key={index}
                  className="flex items-center gap-2 text-primary-foreground"
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.5 + index * 0.1, duration: 0.5 }}
                >
                  <CheckCircle size={20} className="flex-shrink-0" />
                  <span>{benefit}</span>
                </motion.div>
              ))}
            </motion.div>

            {/* CTA Button */}
            <motion.div
              className="pt-4"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.7, duration: 0.6 }}
            >
              <motion.button
                className="group bg-white text-primary px-10 py-4 rounded-full hover:bg-white/90 transition-all shadow-xl hover:shadow-2xl flex items-center gap-2 mx-auto"
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                Próximamente
                <ArrowRight
                  className="group-hover:translate-x-1 transition-transform"
                  size={20}
                />
              </motion.button>
            </motion.div>

            <motion.p
              className="text-primary-foreground/70 text-sm pt-4"
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              transition={{ delay: 0.8, duration: 0.6 }}
            >
              Sin compromiso - Conoce la plataforma antes de decidir
            </motion.p>
          </div>
        </motion.div>
      </div>
    </section>
  );
}

// src/app/components/cta/cta.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { AnimateOnScrollDirective } from '../../directives/animate-on-scroll.directive';

@Component({
  selector: 'app-cta',
  standalone: true,
  imports: [AnimateOnScrollDirective],
  templateUrl: './cta.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CTAComponent {
  benefits = [
    'Acceso anticipado disponible próximamente',
    'Implementación y capacitación incluidas',
    'Soporte técnico especializado',
    'Migración de datos sin costo'
  ];
}


<section class="py-20 md:py-28 px-4 relative overflow-hidden">
  <div class="max-w-5xl mx-auto relative z-10">
    <div
      appAnimateOnScroll
      class="relative bg-gradient-to-br from-[#5a5c8c] via-[#9ca0c7] to-[#5a5c8c] rounded-3xl p-10 md:p-16 lg:p-20 shadow-2xl overflow-hidden animate-on-scroll">
      <!-- Decorative elements -->
      <div class="absolute top-0 right-0 w-96 h-96 bg-white/10 rounded-full blur-3xl animate-pulse"></div>
      <div class="absolute bottom-0 left-0 w-80 h-80 bg-white/10 rounded-full blur-3xl animate-pulse" style="animation-delay: 1s;"></div>
      <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-white/5 rounded-full blur-3xl"></div>

      <!-- Grid pattern overlay -->
      <div class="absolute inset-0 bg-[linear-gradient(to_right,#ffffff08_1px,transparent_1px),linear-gradient(to_bottom,#ffffff08_1px,transparent_1px)] bg-[size:24px_24px]"></div>

      <div class="relative z-10 text-center space-y-8">
        <h2 class="text-4xl md:text-5xl lg:text-6xl text-white font-extrabold leading-tight">
          ¿Listo para <span class="bg-gradient-to-r from-white via-white/90 to-white bg-clip-text text-transparent">modernizar</span> tu práctica médica?
        </h2>

        <p class="text-white/90 text-xl md:text-2xl max-w-3xl mx-auto leading-relaxed">
          Únete a más de 150 clínicas y 2,000 profesionales de la salud que confían en EveryMed
        </p>

        <!-- Benefits -->
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-3xl mx-auto py-8">
          @for (benefit of benefits; track benefit) {
            <div class="flex items-center gap-3 text-white bg-white/10 backdrop-blur-sm rounded-xl px-4 py-3 border border-white/20">
              <span class="text-2xl">✓</span>
              <span class="font-medium">{{ benefit }}</span>
            </div>
          }
        </div>

        <!-- CTA Button -->
        <div class="pt-6">
          <button
            (click)="goToDownload()"
            class="group inline-flex items-center gap-3 bg-white text-[#5a5c8c] px-12 py-5 rounded-2xl hover:bg-white/95 transition-all shadow-2xl hover:shadow-[0_20px_50px_rgba(255,255,255,0.3)] font-bold text-lg hover:scale-105 cursor-pointer">
            Comenzar ahora
            <span class="group-hover:translate-x-1 transition-transform duration-300 text-2xl">→</span>
          </button>
        </div>

        <p class="text-white/80 text-base pt-4">
          Sin compromiso - Conoce la plataforma antes de decidir
        </p>
      </div>
    </div>
  </div>
</section>
