// src/components/Footer.tsx
import React from "react";
import {
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Mail,
  Phone,
  MapPin,
} from "lucide-react";
import svgPaths from "../imports/svg-ugrr49c00q";
import { motion } from "motion/react";

function MedicalIcon() {
  return (
    <svg className="w-8 h-8" fill="none" viewBox="0 0 64 61">
      <path d={svgPaths.p23b25c00} fill="currentColor" />
    </svg>
  );
}

export function Footer() {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.5,
      },
    },
  };

  return (
    <footer className="bg-primary text-primary-foreground py-12 md:py-16 px-4 border-t border-border">
      <div className="max-w-7xl mx-auto">
        <motion.div
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-12"
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
        >
          {/* Brand */}
          <motion.div className="space-y-4" variants={itemVariants}>
            <div className="flex items-center gap-2">
              <MedicalIcon />
              <span className="text-xl">EveryMed</span>
            </div>
            <p className="text-primary-foreground/80">
              Sistema profesional de gestión médica para médicos individuales,
              clínicas y centros de salud.
            </p>
            {/* Social Links */}
            <div className="flex gap-4">
              <motion.a
                href="#"
                className="w-10 h-10 bg-primary-foreground/10 rounded-full flex items-center justify-center hover:bg-primary-foreground/20 transition-colors"
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.95 }}
              >
                <Facebook size={20} />
              </motion.a>
              <motion.a
                href="#"
                className="w-10 h-10 bg-primary-foreground/10 rounded-full flex items-center justify-center hover:bg-primary-foreground/20 transition-colors"
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.95 }}
              >
                <Twitter size={20} />
              </motion.a>
              <motion.a
                href="#"
                className="w-10 h-10 bg-primary-foreground/10 rounded-full flex items-center justify-center hover:bg-primary-foreground/20 transition-colors"
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.95 }}
              >
                <Instagram size={20} />
              </motion.a>
              <motion.a
                href="#"
                className="w-10 h-10 bg-primary-foreground/10 rounded-full flex items-center justify-center hover:bg-primary-foreground/20 transition-colors"
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.95 }}
              >
                <Linkedin size={20} />
              </motion.a>
            </div>
          </motion.div>

          {/* Product */}
          <motion.div variants={itemVariants}>
            <h4 className="mb-4">Producto</h4>
            <ul className="space-y-2">
              <li>
                <a
                  href="#"
                  className="text-primary-foreground/80 hover:text-primary-foreground transition-colors"
                >
                  Características
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-primary-foreground/80 hover:text-primary-foreground transition-colors"
                >
                  Precios
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-primary-foreground/80 hover:text-primary-foreground transition-colors"
                >
                  Seguridad
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-primary-foreground/80 hover:text-primary-foreground transition-colors"
                >
                  Actualizaciones
                </a>
              </li>
            </ul>
          </motion.div>

          {/* Company */}
          <motion.div variants={itemVariants}>
            <h4 className="mb-4">Compañía</h4>
            <ul className="space-y-2">
              <li>
                <a
                  href="#"
                  className="text-primary-foreground/80 hover:text-primary-foreground transition-colors"
                >
                  Sobre Nosotros
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-primary-foreground/80 hover:text-primary-foreground transition-colors"
                >
                  Carreras
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-primary-foreground/80 hover:text-primary-foreground transition-colors"
                >
                  Blog
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-primary-foreground/80 hover:text-primary-foreground transition-colors"
                >
                  Prensa
                </a>
              </li>
            </ul>
          </motion.div>

          {/* Contact */}
          <motion.div variants={itemVariants}>
            <h4 className="mb-4">Contacto</h4>
            <ul className="space-y-3">
              <li className="flex items-start gap-2">
                <Mail size={20} className="flex-shrink-0 mt-1" />
                <a
                  href="mailto:info@everymed.com"
                  className="text-primary-foreground/80 hover:text-primary-foreground transition-colors"
                >
                  info@everymed.com
                </a>
              </li>
              <li className="flex items-start gap-2">
                <Phone size={20} className="flex-shrink-0 mt-1" />
                <a
                  href="tel:+15551234567"
                  className="text-primary-foreground/80 hover:text-primary-foreground transition-colors"
                >
                  +1 (555) 123-4567
                </a>
              </li>
              <li className="flex items-start gap-2">
                <MapPin size={20} className="flex-shrink-0 mt-1" />
                <span className="text-primary-foreground/80">
                  123 Medical Center Dr.
                  <br />
                  San Francisco, CA 94102
                </span>
              </li>
            </ul>
          </motion.div>
        </motion.div>

        {/* Bottom Bar */}
        <motion.div
          className="pt-8 border-t border-primary-foreground/20"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ delay: 0.5, duration: 0.6 }}
        >
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="text-primary-foreground/60 text-sm">
              © 2025 EveryMed. Todos los derechos reservados.
            </p>
            <div className="flex gap-6 text-sm">
              <a
                href="#"
                className="text-primary-foreground/60 hover:text-primary-foreground transition-colors"
              >
                Privacidad
              </a>
              <a
                href="#"
                className="text-primary-foreground/60 hover:text-primary-foreground transition-colors"
              >
                Términos
              </a>
              <a
                href="#"
                className="text-primary-foreground/60 hover:text-primary-foreground transition-colors"
              >
                Cookies
              </a>
            </div>
          </div>
        </motion.div>
      </div>
    </footer>
  );
}

// src/app/components/footer/footer.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './footer.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'block w-full shrink-0' },
})
export class FooterComponent {
  protected readonly currentYear = new Date().getFullYear();
}


<footer class="relative bg-white/60 dark:bg-gray-900/60 backdrop-blur-xl border-t border-gray-200/50 dark:border-gray-700/50 transition-colors duration-300 overflow-hidden">
  <!-- Background decorative elements -->
  <div class="absolute inset-0 overflow-hidden pointer-events-none">
    <div class="absolute bottom-0 left-0 w-96 h-96 bg-[#5a5c8c] rounded-full blur-[120px] opacity-5 dark:opacity-10"></div>
    <div class="absolute bottom-0 right-0 w-[500px] h-[500px] bg-[#9ca0c7] rounded-full blur-[140px] opacity-5 dark:opacity-10"></div>
  </div>

  <div class="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 md:gap-12">
      <!-- Brand Section -->
      <div class="lg:col-span-1">
        <a href="#inicio" class="flex items-center gap-2.5 mb-4 group cursor-pointer">
          <div class="relative w-10 h-10 sm:w-12 sm:h-12">
            <div class="absolute inset-0 rounded-xl bg-gradient-to-br from-[#5a5c8c]/30 via-[#9ca0c7]/15 to-[#5a5c8c]/30 dark:from-[#9ca0c7]/40 dark:via-[#5a5c8c]/25 dark:to-[#9ca0c7]/40 blur-md opacity-70"></div>
            <div class="absolute inset-0 rounded-xl bg-gradient-to-br from-[#5a5c8c]/10 to-transparent dark:from-[#9ca0c7]/20 dark:to-transparent"></div>
            <div class="relative w-full h-full rounded-xl bg-gradient-to-br from-[#5a5c8c]/8 via-[#9ca0c7]/5 to-[#5a5c8c]/8 dark:from-[#9ca0c7]/15 dark:via-[#5a5c8c]/8 dark:to-[#9ca0c7]/15 border border-[#5a5c8c]/25 dark:border-[#9ca0c7]/35 flex items-center justify-center shadow-lg shadow-[#5a5c8c]/20 dark:shadow-[#9ca0c7]/30 backdrop-blur-sm transition-all duration-300 group-hover:scale-105">
              <img src="/assets/icons-app/everymed-icon/logo-everymed-claro.svg" alt="EveryMed Logo"
                class="w-6 h-6 sm:w-7 sm:h-7 object-contain block dark:hidden drop-shadow-sm" />
              <img src="/assets/icons-app/everymed-icon/logo-everymed-obscuro.svg" alt="EveryMed Logo"
                class="w-6 h-6 sm:w-7 sm:h-7 object-contain hidden dark:block drop-shadow-sm" />
            </div>
          </div>
          <div>
            <h2 class="font-bold text-lg sm:text-xl leading-tight">
              <span class="bg-gradient-to-r from-[#5a5c8c] via-[#9ca0c7] to-[#5a5c8c] dark:from-[#9ca0c7] dark:via-[#5a5c8c] dark:to-[#9ca0c7] bg-clip-text text-transparent drop-shadow-sm">
                Every
              </span>
              <span class="text-[#5a5c8c] dark:text-[#9ca0c7] drop-shadow-sm">Med</span>
            </h2>
          </div>
        </a>
        <p class="text-sm text-gray-600 dark:text-gray-400 mb-6 leading-relaxed">
          Plataforma integral de gestión médica diseñada para médicos, clínicas y centros de salud modernos.
        </p>
        <!-- Social Links -->
        <div class="flex items-center gap-4">
          <a href="https://github.com/EveryMed" target="_blank" rel="noopener noreferrer"
            class="w-10 h-10 rounded-xl bg-gradient-to-br from-[#5a5c8c]/10 to-[#9ca0c7]/10 dark:from-[#9ca0c7]/20 dark:to-[#5a5c8c]/20 flex items-center justify-center text-gray-700 dark:text-gray-300 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] hover:bg-gradient-to-br hover:from-[#5a5c8c]/20 hover:to-[#9ca0c7]/20 dark:hover:from-[#9ca0c7]/30 dark:hover:to-[#5a5c8c]/30 transition-all duration-300 hover:scale-110 shadow-md hover:shadow-lg cursor-pointer"
            aria-label="GitHub">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path
                d="M12 0C5.374 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0112 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z" />
            </svg>
          </a>
          <a href="https://www.linkedin.com" target="_blank" rel="noopener noreferrer"
            class="w-10 h-10 rounded-xl bg-gradient-to-br from-[#5a5c8c]/10 to-[#9ca0c7]/10 dark:from-[#9ca0c7]/20 dark:to-[#5a5c8c]/20 flex items-center justify-center text-gray-700 dark:text-gray-300 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] hover:bg-gradient-to-br hover:from-[#5a5c8c]/20 hover:to-[#9ca0c7]/20 dark:hover:from-[#9ca0c7]/30 dark:hover:to-[#5a5c8c]/30 transition-all duration-300 hover:scale-110 shadow-md hover:shadow-lg cursor-pointer"
            aria-label="LinkedIn">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path
                d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
            </svg>
          </a>
        </div>
      </div>

      <!-- Navigation Links -->
      <div>
        <h3 class="text-base font-bold text-gray-900 dark:text-white mb-4">Navegación</h3>
        <ul class="space-y-3">
          <li>
            <a href="#inicio" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 flex items-center gap-2 group cursor-pointer">
              <span class="w-1.5 h-1.5 rounded-full bg-[#5a5c8c]/30 dark:bg-[#9ca0c7]/30 group-hover:bg-[#5a5c8c] dark:group-hover:bg-[#9ca0c7] transition-colors"></span>
              Inicio
            </a>
          </li>
          <li>
            <a href="#servicios" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 flex items-center gap-2 group cursor-pointer">
              <span class="w-1.5 h-1.5 rounded-full bg-[#5a5c8c]/30 dark:bg-[#9ca0c7]/30 group-hover:bg-[#5a5c8c] dark:group-hover:bg-[#9ca0c7] transition-colors"></span>
              Servicios
            </a>
          </li>
          <li>
            <a href="#planes" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 flex items-center gap-2 group cursor-pointer">
              <span class="w-1.5 h-1.5 rounded-full bg-[#5a5c8c]/30 dark:bg-[#9ca0c7]/30 group-hover:bg-[#5a5c8c] dark:group-hover:bg-[#9ca0c7] transition-colors"></span>
              Planes
            </a>
          </li>
          <li>
            <a href="#equipo" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 flex items-center gap-2 group cursor-pointer">
              <span class="w-1.5 h-1.5 rounded-full bg-[#5a5c8c]/30 dark:bg-[#9ca0c7]/30 group-hover:bg-[#5a5c8c] dark:group-hover:bg-[#9ca0c7] transition-colors"></span>
              Equipo
            </a>
          </li>
          <li>
            <a href="#contacto" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 flex items-center gap-2 group cursor-pointer">
              <span class="w-1.5 h-1.5 rounded-full bg-[#5a5c8c]/30 dark:bg-[#9ca0c7]/30 group-hover:bg-[#5a5c8c] dark:group-hover:bg-[#9ca0c7] transition-colors"></span>
              Contacto
            </a>
          </li>
        </ul>
      </div>

      <!-- Legal Links -->
      <div>
        <h3 class="text-base font-bold text-gray-900 dark:text-white mb-4">Legal</h3>
        <ul class="space-y-3">
          <li>
            <a routerLink="/legal/terminos" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 flex items-center gap-2 group cursor-pointer">
              <span class="w-1.5 h-1.5 rounded-full bg-[#5a5c8c]/30 dark:bg-[#9ca0c7]/30 group-hover:bg-[#5a5c8c] dark:group-hover:bg-[#9ca0c7] transition-colors"></span>
              Términos de Servicio
            </a>
          </li>
          <li>
            <a routerLink="/legal/privacidad" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 flex items-center gap-2 group cursor-pointer">
              <span class="w-1.5 h-1.5 rounded-full bg-[#5a5c8c]/30 dark:bg-[#9ca0c7]/30 group-hover:bg-[#5a5c8c] dark:group-hover:bg-[#9ca0c7] transition-colors"></span>
              Política de Privacidad
            </a>
          </li>
          <li>
            <a routerLink="/legal/cookies" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 flex items-center gap-2 group cursor-pointer">
              <span class="w-1.5 h-1.5 rounded-full bg-[#5a5c8c]/30 dark:bg-[#9ca0c7]/30 group-hover:bg-[#5a5c8c] dark:group-hover:bg-[#9ca0c7] transition-colors"></span>
              Política de Cookies
            </a>
          </li>
          <li>
            <a routerLink="/legal/aviso-legal" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 flex items-center gap-2 group cursor-pointer">
              <span class="w-1.5 h-1.5 rounded-full bg-[#5a5c8c]/30 dark:bg-[#9ca0c7]/30 group-hover:bg-[#5a5c8c] dark:group-hover:bg-[#9ca0c7] transition-colors"></span>
              Aviso Legal
            </a>
          </li>
        </ul>
      </div>

      <!-- Contact Info -->
      <div>
        <h3 class="text-base font-bold text-gray-900 dark:text-white mb-4">Contacto</h3>
        <ul class="space-y-3">
          <li class="flex items-start gap-3">
            <svg class="w-5 h-5 text-[#5a5c8c] dark:text-[#9ca0c7] mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
            <a href="mailto:everymed@gmail.com" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 cursor-pointer">
              everymed@gmail.com
            </a>
          </li>
          <li class="flex items-start gap-3">
            <svg class="w-5 h-5 text-[#5a5c8c] dark:text-[#9ca0c7] mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
            </svg>
            <a href="tel:7714315837" class="text-sm text-gray-600 dark:text-gray-400 hover:text-[#5a5c8c] dark:hover:text-[#9ca0c7] transition-colors duration-200 cursor-pointer">
              7714315837
            </a>
          </li>
        </ul>
      </div>
    </div>

    <!-- Bottom Bar -->
    <div class="mt-12 pt-8 border-t border-gray-200/50 dark:border-gray-700/50 flex flex-col sm:flex-row items-center justify-between gap-4">
      <p class="text-sm text-gray-600 dark:text-gray-400 text-center sm:text-left">
        &copy; {{ currentYear }} EveryMed. Todos los derechos reservados.
      </p>
      <p class="text-sm text-gray-600 dark:text-gray-400 text-center sm:text-right flex items-center justify-center sm:justify-end gap-1.5">
        Hecho con 
        <svg class="w-4 h-4 text-[#5a5c8c] dark:text-[#9ca0c7]" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z" />
        </svg>
        para profesionales de la salud
      </p>
    </div>
  </div>
</footer>
