// src/components/Hero.tsx
import React from "react";
import { ArrowRight, Play } from "lucide-react";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { motion } from "motion/react";

export function Hero() {
  return (
    <section id="inicio" className="relative pt-28 pb-16 md:pt-36 md:pb-24 px-4 overflow-hidden">
      <div className="max-w-7xl mx-auto">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          {/* Left Content */}
          <motion.div 
            className="space-y-6 md:space-y-8"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <motion.h1 
              className="text-4xl md:text-5xl lg:text-6xl text-foreground leading-tight"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.6 }}
            >
              Gestión médica para{" "}
              <span className="text-primary">todos los tamaños</span>
            </motion.h1>

            <motion.p 
              className="text-lg text-muted-foreground"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3, duration: 0.6 }}
            >
              Plataforma integral de administración médica diseñada para médicos individuales, 
              clínicas pequeñas y grandes centros de salud. Gestiona historiales clínicos, 
              citas, pacientes y tu equipo médico desde una sola plataforma.
            </motion.p>

            <motion.div 
              className="flex flex-col sm:flex-row gap-4"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4, duration: 0.6 }}
            >
              <motion.button 
                className="group bg-primary text-primary-foreground px-8 py-4 rounded-full hover:opacity-90 transition-all shadow-lg hover:shadow-xl flex items-center justify-center gap-2"
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                Comenzar ahora
                <ArrowRight className="group-hover:translate-x-1 transition-transform" size={20} />
              </motion.button>
              <motion.button 
                className="group bg-card text-foreground px-8 py-4 rounded-full border-2 border-border hover:border-primary hover:bg-accent transition-all flex items-center justify-center gap-2 shadow-md"
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                <Play size={20} />
                Próximamente
              </motion.button>
            </motion.div>

            {/* Trust Indicators */}
            <motion.div 
              className="flex flex-wrap items-center gap-6 pt-8"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.6, duration: 0.6 }}
            >
              <div className="flex items-center gap-2">
                <div className="flex -space-x-2">
                  {[1, 2, 3, 4].map((i) => (
                    <div 
                      key={i} 
                      className="w-8 h-8 rounded-full bg-primary/20 border-2 border-background flex items-center justify-center text-xs text-primary"
                    >
                      {i === 1 ? '👨‍⚕️' : i === 2 ? '👩‍⚕️' : i === 3 ? '👨‍⚕️' : '👩‍⚕️'}
                    </div>
                  ))}
                </div>
                <p className="text-sm text-muted-foreground">
                  +2,000 médicos confían en nosotros
                </p>
              </div>
            </motion.div>
          </motion.div>

          {/* Right Content - Image Placeholder */}
          <motion.div 
            className="relative"
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4, duration: 0.8 }}
          >
            <div className="relative z-10">
              <motion.div 
                className="bg-gradient-to-br from-primary/20 via-secondary/20 to-accent/20 rounded-3xl p-8 shadow-2xl border border-border backdrop-blur-sm"
                whileHover={{ scale: 1.02 }}
                transition={{ duration: 0.3 }}
              >
                <ImageWithFallback
                  src="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop"
                  alt="Medical professionals"
                  className="w-full h-auto rounded-2xl shadow-lg"
                />
              </motion.div>
            </div>
            {/* Decorative elements */}
            <motion.div 
              className="absolute -top-4 -right-4 w-24 h-24 bg-secondary rounded-full blur-2xl opacity-30"
              animate={{ 
                scale: [1, 1.2, 1],
                opacity: [0.3, 0.2, 0.3]
              }}
              transition={{ 
                duration: 4,
                repeat: Infinity,
                ease: "easeInOut"
              }}
            ></motion.div>
            <motion.div 
              className="absolute -bottom-4 -left-4 w-32 h-32 bg-primary rounded-full blur-3xl opacity-20"
              animate={{ 
                scale: [1, 1.3, 1],
                opacity: [0.2, 0.3, 0.2]
              }}
              transition={{ 
                duration: 5,
                repeat: Infinity,
                ease: "easeInOut"
              }}
            ></motion.div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}

// src/app/components/hero/hero.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AnimateOnScrollDirective } from '../../directives/animate-on-scroll.directive';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [AnimateOnScrollDirective, RouterLink],
  templateUrl: './hero.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeroComponent {
  getIcons(): Array<'male' | 'female'> {
    return ['male', 'female', 'male', 'female'];
  }
}


<section id="inicio" class="relative px-4 overflow-hidden min-h-[calc(100vh-3.5rem)] sm:min-h-[calc(100vh-4rem)] flex items-center py-12 md:py-16">
  <!-- Background decorative elements -->
  <div class="absolute inset-0 overflow-hidden pointer-events-none">
    <!-- Animated gradient orbs -->
    <div class="absolute top-1/4 -left-1/4 w-96 h-96 bg-[#5a5c8c] rounded-full blur-[120px] opacity-20 dark:opacity-30 animate-pulse"></div>
    <div class="absolute bottom-1/4 -right-1/4 w-[500px] h-[500px] bg-[#9ca0c7] rounded-full blur-[140px] opacity-20 dark:opacity-30 animate-pulse" style="animation-delay: 1s;"></div>
    <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gradient-to-r from-[#5a5c8c]/10 to-[#9ca0c7]/10 rounded-full blur-[150px] opacity-30"></div>
    
    <!-- Grid pattern overlay -->
    <div class="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px] dark:opacity-20"></div>
  </div>

  <div class="max-w-7xl mx-auto relative z-10 w-full">
    <div class="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
      <!-- Left Content -->
      <div 
        appAnimateOnScroll
        class="space-y-8 md:space-y-10 animate-on-scroll">
        <!-- Badge -->
        <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gradient-to-r from-[#5a5c8c]/10 via-[#9ca0c7]/10 to-[#5a5c8c]/10 dark:from-[#9ca0c7]/20 dark:via-[#5a5c8c]/20 dark:to-[#9ca0c7]/20 backdrop-blur-sm border border-[#5a5c8c]/20 dark:border-[#9ca0c7]/30">
          <span class="w-2 h-2 rounded-full bg-[#5a5c8c] dark:bg-[#9ca0c7] animate-pulse"></span>
          <span class="text-sm font-medium text-[#5a5c8c] dark:text-[#9ca0c7]">Plataforma médica integral</span>
        </div>

        <!-- Main Heading -->
        <h1 class="text-5xl md:text-6xl lg:text-7xl font-extrabold leading-tight tracking-tight">
          <span class="block text-gray-900 dark:text-white">Gestión médica</span>
          <span class="block bg-gradient-to-r from-[#5a5c8c] via-[#9ca0c7] to-[#5a5c8c] dark:from-[#9ca0c7] dark:via-[#5a5c8c] dark:to-[#9ca0c7] bg-clip-text text-transparent">
            para todos
          </span>
          <span class="block text-gray-900 dark:text-white">los tamaños</span>
        </h1>

        <!-- Description -->
        <p class="text-xl md:text-2xl text-gray-600 dark:text-gray-300 leading-relaxed max-w-2xl">
          Plataforma integral diseñada para médicos individuales, clínicas pequeñas y grandes centros de salud. 
          <span class="text-[#5a5c8c] dark:text-[#9ca0c7] font-semibold">Gestiona todo desde un solo lugar.</span>
        </p>

        <!-- CTA Buttons -->
        <div class="flex flex-col sm:flex-row gap-4 pt-4">
          <a 
            href="#contacto"
            class="group relative px-8 py-4 rounded-2xl bg-gradient-to-r from-[#5a5c8c] to-[#9ca0c7] text-white font-semibold text-lg shadow-xl shadow-[#5a5c8c]/30 dark:shadow-[#9ca0c7]/30 hover:shadow-2xl hover:shadow-[#5a5c8c]/40 dark:hover:shadow-[#9ca0c7]/40 transition-all duration-300 flex items-center justify-center gap-2 overflow-hidden cursor-pointer">
            <span class="relative z-10 flex items-center gap-2">
              Comenzar ahora
              <span class="group-hover:translate-x-1 transition-transform duration-300">→</span>
            </span>
            <div class="absolute inset-0 bg-gradient-to-r from-[#9ca0c7] to-[#5a5c8c] opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
          </a>
          <a 
            routerLink="/demo"
            class="group px-8 py-4 rounded-2xl bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm text-gray-900 dark:text-white font-semibold text-lg border-2 border-gray-200 dark:border-gray-700 hover:border-[#5a5c8c] dark:hover:border-[#9ca0c7] hover:bg-white dark:hover:bg-gray-800 transition-all duration-300 flex items-center justify-center gap-2 shadow-lg hover:shadow-xl cursor-pointer">
            <span class="text-[#5a5c8c] dark:text-[#9ca0c7]">▶</span>
            Ver demo
          </a>
        </div>

        <!-- Trust Indicators -->
        <div class="flex flex-wrap items-center gap-8 pt-8 border-t border-gray-200/50 dark:border-gray-700/50">
          <div class="flex items-center gap-3">
            <div class="flex -space-x-3">
              @for (iconType of getIcons(); track $index) {
                <div class="w-10 h-10 rounded-full bg-gradient-to-br from-[#5a5c8c]/20 to-[#9ca0c7]/20 dark:from-[#9ca0c7]/30 dark:to-[#5a5c8c]/30 border-2 border-white dark:border-gray-800 flex items-center justify-center shadow-md backdrop-blur-sm">
                  @if (iconType === 'male') {
                    <svg class="w-5 h-5 text-[#5a5c8c] dark:text-[#9ca0c7]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                  } @else {
                    <svg class="w-5 h-5 text-[#5a5c8c] dark:text-[#9ca0c7]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
                    </svg>
                  }
                </div>
              }
            </div>
            <div class="flex flex-col">
              <p class="text-sm font-semibold text-gray-900 dark:text-white">
                +2,000 médicos
              </p>
              <p class="text-xs text-gray-600 dark:text-gray-400">
                confían en nosotros
              </p>
            </div>
          </div>
          <div class="h-12 w-px bg-gray-200 dark:bg-gray-700"></div>
          <div class="flex flex-col">
            <p class="text-sm font-semibold text-gray-900 dark:text-white">
              +150 clínicas
            </p>
            <p class="text-xs text-gray-600 dark:text-gray-400">
              activas en la plataforma
            </p>
          </div>
        </div>
      </div>

      <!-- Right Content - Visual Showcase -->
      <div 
        appAnimateOnScroll
        class="relative animate-on-scroll animate-delay-200">
        <!-- Main card container -->
        <div class="relative z-10">
          <div class="relative bg-white/60 dark:bg-gray-900/60 backdrop-blur-xl rounded-3xl p-6 md:p-8 shadow-2xl border border-white/20 dark:border-gray-700/30 overflow-hidden">
            <!-- Inner gradient border effect -->
            <div class="absolute inset-0 rounded-3xl bg-gradient-to-r from-[#5a5c8c]/20 via-[#9ca0c7]/20 to-[#5a5c8c]/20 dark:from-[#9ca0c7]/30 dark:via-[#5a5c8c]/30 dark:to-[#9ca0c7]/30 opacity-50 blur-xl"></div>
            
            <!-- Content area -->
            <div class="relative z-10 w-full rounded-2xl overflow-hidden shadow-inner">
              <!-- Imagen del dashboard - Modo Claro -->
              <img 
                src="/assets/images/dashboard_claro.png" 
                alt="Dashboard EveryMed - Modo Claro"
                class="w-full h-auto object-contain dark:hidden"
              />
              <!-- Imagen del dashboard - Modo Oscuro -->
              <img 
                src="/assets/images/dashboard_obscuro.png" 
                alt="Dashboard EveryMed - Modo Oscuro"
                class="w-full h-auto object-contain hidden dark:block"
              />
            </div>

            <!-- Descripción del dashboard -->
            <div class="relative z-10 mt-6 text-center">
              <h3 class="text-xl md:text-2xl font-bold text-gray-900 dark:text-white mb-2">
                Dashboard EveryMed
              </h3>
              <p class="text-sm md:text-base text-gray-600 dark:text-gray-400">
                Vista previa de la plataforma - Gestión completa de tu clínica desde un solo lugar
              </p>
            </div>

            <!-- Floating elements -->
            <div class="absolute -top-4 -right-4 w-24 h-24 bg-gradient-to-br from-[#9ca0c7] to-[#5a5c8c] rounded-2xl blur-2xl opacity-40 animate-pulse"></div>
            <div class="absolute -bottom-4 -left-4 w-32 h-32 bg-gradient-to-br from-[#5a5c8c] to-[#9ca0c7] rounded-2xl blur-3xl opacity-30 animate-pulse" style="animation-delay: 1.5s;"></div>
          </div>
        </div>

        <!-- Decorative floating cards -->
        <div class="absolute -bottom-8 -left-8 w-32 h-32 bg-gradient-to-br from-[#5a5c8c]/30 to-[#9ca0c7]/30 dark:from-[#9ca0c7]/40 dark:to-[#5a5c8c]/40 rounded-2xl backdrop-blur-md border border-white/20 dark:border-gray-700/30 shadow-xl rotate-12 hidden md:block"></div>
        <div class="absolute -top-8 -right-8 w-28 h-28 bg-gradient-to-br from-[#9ca0c7]/30 to-[#5a5c8c]/30 dark:from-[#5a5c8c]/40 dark:to-[#9ca0c7]/40 rounded-2xl backdrop-blur-md border border-white/20 dark:border-gray-700/30 shadow-xl -rotate-12 hidden md:block"></div>
      </div>
    </div>
  </div>
</section>
