// src/components/Plans.tsx
import React, { useState } from "react";
import { User, Building, Building2, Users, Check, Sparkles, Gift } from "lucide-react";
import { motion } from "motion/react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { Checkbox } from "./ui/checkbox";
import { Separator } from "./ui/separator";

export function Plans() {
  const [activeTab, setActiveTab] = useState("individual");

  const addOns = [
    { id: "chat", label: "Chat con los pacientes" },
    { id: "pharmacy", label: "Administración de farmacia" },
    { id: "reports", label: "Reportes avanzados" },
    { id: "lab", label: "Integración con laboratorios" },
    { id: "telemedicine", label: "Telemedicina" }
  ];

  const individualPlans = [
    {
      icon: Gift,
      name: "Gratis",
      price: "$0",
      period: "/mes",
      description: "Comienza sin costo",
      features: [
        "Gestión de expedientes básicos",
        "Agenda simple para citas"
      ],
      isFree: true
    },
    {
      icon: User,
      name: "Plan Individual",
      price: "$125.00",
      period: "/mes",
      description: "Perfecto para médicos independientes",
      features: [
        "Agenda para gestión de pacientes",
        "Generación de recetas médicas",
        "Historial clínico completo",
        "Recordatorios automáticos",
        "Soporte técnico incluido"
      ],
      isFree: false
    }
  ];

  const businessPlans = [
    {
      icon: Building,
      name: "Clínica Pequeña",
      users: "2",
      price: "$300",
      period: "/mes",
      description: "Ideal para clínicas en crecimiento",
      features: [
        "Chat Doctor-Paciente",
        "Gestión de inventario",
        "Control de finanzas",
        "Recetas y expedientes",
        "Gestión de agenda",
        "Administración de equipo"
      ],
      popular: false
    },
    {
      icon: Building2,
      name: "Clínica Mediana",
      users: "3-5",
      price: "$600",
      period: "/mes",
      description: "Para clínicas establecidas",
      features: [
        "Todo del plan Pequeña",
        "Gestión avanzada de pacientes",
        "Expedientes digitales completos",
        "Búsqueda de clínica en app",
        "Perfil con ubicación (Google Maps)",
        "Sistema de reseñas",
        "Reportes analíticos"
      ],
      popular: true
    },
    {
      icon: Users,
      name: "Clínica Grande",
      users: "6-10",
      price: "$1,000",
      period: "/mes",
      description: "Para instituciones grandes",
      features: [
        "Todo del plan Mediana",
        "Múltiples especialidades",
        "Gestión multi-sede",
        "Servicios destacados en búsqueda",
        "API personalizada",
        "Capacitación del equipo",
        "Soporte prioritario 24/7"
      ],
      popular: false
    },
    {
      icon: Sparkles,
      name: "Enterprise",
      users: "+10",
      price: "Personalizado",
      period: "",
      description: "Solución personalizada",
      features: [
        "Configuración 100% personalizada",
        "Integración con sistemas existentes",
        "Infraestructura dedicada",
        "SLA garantizado",
        "Gestor de cuenta dedicado",
        "Desarrollo de funciones a medida",
        "Consultoría estratégica"
      ],
      popular: false,
      isCustom: true
    }
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15
      }
    }
  };

  const cardVariants = {
    hidden: { opacity: 0, y: 50 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.6,
        ease: "easeOut"
      }
    }
  };

  return (
    <section id="planes" className="py-16 md:py-24 px-4 bg-background">
      <div className="max-w-7xl mx-auto">
        {/* Section Header */}
        <motion.div 
          className="text-center mb-12 md:mb-16"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
        >
          <motion.div 
            className="inline-block mb-4"
            initial={{ opacity: 0, scale: 0.8 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2, duration: 0.5 }}
          >
            <span className="bg-accent text-accent-foreground px-4 py-2 rounded-full">
              Planes y Precios
            </span>
          </motion.div>
          <motion.h2 
            className="text-3xl md:text-4xl text-foreground mb-4"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.3, duration: 0.6 }}
          >
            Un plan para cada necesidad
          </motion.h2>
          <motion.p 
            className="text-muted-foreground max-w-2xl mx-auto"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.4, duration: 0.6 }}
          >
            Desde médicos independientes hasta grandes centros de salud, tenemos la solución perfecta para ti
          </motion.p>
        </motion.div>

        {/* Tabs for Individual and Business */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.5, duration: 0.6 }}
        >
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="grid w-full max-w-md mx-auto grid-cols-2 mb-12">
              <TabsTrigger value="individual" className="gap-2">
                <User size={18} />
                Individual
              </TabsTrigger>
              <TabsTrigger value="empresa" className="gap-2">
                <Building size={18} />
                Empresa
              </TabsTrigger>
            </TabsList>

            {/* Individual Plans */}
            <TabsContent value="individual">
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.4 }}
                className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto"
              >
                {individualPlans.map((plan, index) => {
                  const Icon = plan.icon;
                  return (
                    <motion.div
                      key={index}
                      className={`relative p-8 rounded-2xl border-2 shadow-xl ${
                        plan.isFree
                          ? 'border-border bg-card hover:border-primary/50'
                          : 'border-primary bg-gradient-to-br from-primary/10 to-secondary/10'
                      }`}
                      whileHover={{ 
                        y: -10,
                        scale: 1.02,
                        transition: { duration: 0.3 }
                      }}
                    >
                      {!plan.isFree && (
                        <div className="absolute -top-4 left-1/2 -translate-x-1/2 bg-primary text-primary-foreground px-4 py-1 rounded-full text-sm">
                          Recomendado
                        </div>
                      )}

                      <div className="flex flex-col items-center text-center mb-6">
                        <div className={`w-16 h-16 rounded-2xl flex items-center justify-center mb-4 ${
                          plan.isFree ? 'bg-accent' : 'bg-primary'
                        }`}>
                          <Icon className={plan.isFree ? 'text-foreground' : 'text-primary-foreground'} size={32} />
                        </div>
                        <h3 className="text-foreground mb-2">
                          {plan.name}
                        </h3>
                        <p className="text-muted-foreground text-sm mb-4">
                          {plan.description}
                        </p>
                        <div className="flex items-end gap-1">
                          <span className={`text-4xl ${plan.isFree ? 'text-foreground' : 'text-primary'}`}>
                            {plan.price}
                          </span>
                          <span className="text-muted-foreground mb-1">
                            {plan.period}
                          </span>
                        </div>
                      </div>

                      <ul className="space-y-3 mb-6">
                        {plan.features.map((feature, idx) => (
                          <li key={idx} className="flex items-start gap-3">
                            <Check className={`flex-shrink-0 mt-0.5 ${
                              plan.isFree ? 'text-muted-foreground' : 'text-primary'
                            }`} size={20} />
                            <span className="text-foreground text-sm">
                              {feature}
                            </span>
                          </li>
                        ))}
                      </ul>

                      {/* Add-ons Section */}
                      <div className="mb-6">
                        <Separator className="mb-4" />
                        <h4 className="text-sm text-muted-foreground mb-3">Complementos</h4>
                        <div className="space-y-2.5">
                          {addOns.map((addon) => (
                            <div key={addon.id} className="flex items-center gap-2">
                              <Checkbox id={`${plan.name}-${addon.id}`} />
                              <label
                                htmlFor={`${plan.name}-${addon.id}`}
                                className="text-sm text-foreground cursor-pointer"
                              >
                                {addon.label}
                              </label>
                            </div>
                          ))}
                        </div>
                      </div>

                      <motion.a
                        href="https://everymed.com"
                        target="_blank"
                        rel="noopener noreferrer"
                        className={`block w-full py-3 rounded-full text-center transition-all ${
                          plan.isFree
                            ? 'bg-accent text-accent-foreground hover:bg-accent/80'
                            : 'bg-primary text-primary-foreground hover:opacity-90'
                        }`}
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                      >
                        Próximamente
                      </motion.a>
                    </motion.div>
                  );
                })}
              </motion.div>
            </TabsContent>

            {/* Business Plans */}
            <TabsContent value="empresa">
              <motion.div 
                className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
                variants={containerVariants}
                initial="hidden"
                animate="visible"
              >
                {businessPlans.map((plan, index) => {
                  const Icon = plan.icon;
                  return (
                    <motion.div
                      key={index}
                      variants={cardVariants}
                      className={`relative p-6 rounded-2xl border-2 transition-all duration-300 hover:shadow-2xl ${
                        plan.popular
                          ? 'border-primary bg-gradient-to-br from-primary/10 to-secondary/10 scale-105'
                          : 'border-border bg-card hover:border-primary/50'
                      }`}
                      whileHover={{ 
                        y: -10,
                        scale: plan.popular ? 1.05 : 1.03,
                        transition: { duration: 0.3 }
                      }}
                    >
                      {plan.popular && (
                        <div className="absolute -top-4 left-1/2 -translate-x-1/2 bg-primary text-primary-foreground px-4 py-1 rounded-full text-sm">
                          Más popular
                        </div>
                      )}

                      <div className="flex flex-col items-center text-center mb-6">
                        <div className={`w-14 h-14 rounded-2xl flex items-center justify-center mb-4 ${
                          plan.popular ? 'bg-primary' : 'bg-accent'
                        }`}>
                          <Icon className={plan.popular ? 'text-primary-foreground' : 'text-foreground'} size={28} />
                        </div>
                        <h3 className="text-foreground mb-1 text-lg">
                          {plan.name}
                        </h3>
                        <div className={`px-3 py-1 rounded-full mb-3 ${
                          plan.isCustom 
                            ? 'bg-gradient-to-r from-primary to-secondary' 
                            : 'bg-accent'
                        }`}>
                          <span className={`text-sm ${
                            plan.isCustom ? 'text-white' : 'text-foreground'
                          }`}>
                            {plan.users} usuarios
                          </span>
                        </div>
                        <div className="flex items-end gap-1 mb-2">
                          <span className={`text-2xl ${plan.popular ? 'text-primary' : 'text-foreground'}`}>
                            {plan.price}
                          </span>
                          {plan.period && (
                            <span className="text-muted-foreground text-sm mb-0.5">
                              {plan.period}
                            </span>
                          )}
                        </div>
                        <p className="text-muted-foreground text-sm">
                          {plan.description}
                        </p>
                      </div>

                      <ul className="space-y-2.5 mb-4">
                        {plan.features.map((feature, idx) => (
                          <li key={idx} className="flex items-start gap-2">
                            <Check className={`flex-shrink-0 mt-0.5 ${
                              plan.popular ? 'text-primary' : 'text-muted-foreground'
                            }`} size={18} />
                            <span className="text-foreground text-sm">
                              {feature}
                            </span>
                          </li>
                        ))}
                      </ul>

                      {/* Add-ons Section */}
                      <div className="mb-4">
                        <Separator className="mb-3" />
                        <h4 className="text-xs text-muted-foreground mb-2.5">Complementos</h4>
                        <div className="space-y-2">
                          {addOns.slice(0, 3).map((addon) => (
                            <div key={addon.id} className="flex items-center gap-2">
                              <Checkbox id={`${plan.name}-${addon.id}`} />
                              <label
                                htmlFor={`${plan.name}-${addon.id}`}
                                className="text-xs text-foreground cursor-pointer"
                              >
                                {addon.label}
                              </label>
                            </div>
                          ))}
                        </div>
                      </div>

                      <motion.a
                        href={plan.isCustom ? '#contacto' : 'https://everymed.com'}
                        target={plan.isCustom ? '_self' : '_blank'}
                        rel={plan.isCustom ? undefined : 'noopener noreferrer'}
                        className={`block w-full py-2.5 rounded-full text-center transition-all text-sm ${
                          plan.popular
                            ? 'bg-primary text-primary-foreground hover:opacity-90'
                            : plan.isCustom
                            ? 'bg-gradient-to-r from-primary to-secondary text-white hover:opacity-90'
                            : 'bg-accent text-accent-foreground hover:bg-accent/80'
                        }`}
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                      >
                        {plan.isCustom ? 'Contactar Ventas' : 'Próximamente'}
                      </motion.a>
                    </motion.div>
                  );
                })}
              </motion.div>
            </TabsContent>
          </Tabs>
        </motion.div>

        {/* Bottom CTA */}
        <motion.div 
          className="mt-12 text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.6, duration: 0.6 }}
        >
          <p className="text-muted-foreground mb-4">
            ¿Necesitas un plan personalizado para tu institución?
          </p>
          <motion.button 
            className="text-primary hover:underline"
            whileHover={{ x: 5 }}
            transition={{ duration: 0.2 }}
          >
            Contacta con nuestro equipo de ventas →
          </motion.button>
        </motion.div>
      </div>
    </section>
  );
}

// src/app/components/plans/plans.component.ts
import { Component, ChangeDetectionStrategy, signal } from '@angular/core';
import { AnimateOnScrollDirective } from '../../directives/animate-on-scroll.directive';
import { CommonModule } from '@angular/common';
import { TabNavigationComponent } from '../../shared/components/tab-navigation/tab-navigation.component';
import {
  PlanCardComponent,
  CaracteristicaPlan,
  ComplementoPlan,
} from '../../shared/components/plan-card/plan-card.component';
import { TipoPlan, PESTANAS_PLAN } from '../../shared/interfaces/plans.interface';

@Component({
  selector: 'app-plans',
  standalone: true,
  imports: [AnimateOnScrollDirective, CommonModule, TabNavigationComponent, PlanCardComponent],
  templateUrl: './plans.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlansComponent {
  readonly PESTANAS_PLAN = PESTANAS_PLAN;
  planActivo = signal<TipoPlan>('Individual');

  caracteristicasPlanGratis: CaracteristicaPlan[] = [
    { texto: 'Con anuncios', destacada: true },
    { texto: 'Gestión de expedientes básicos' },
    { texto: 'Agenda simple para citas' },
  ];

  complementosPlanGratis: ComplementoPlan[] = [];

  caracteristicasPlanIndividual: CaracteristicaPlan[] = [
    { texto: 'Sin anuncios - Experiencia premium', destacada: true },
    { texto: 'Agenda para gestión de pacientes' },
    { texto: 'Generación de recetas médicas' },
    { texto: 'Historial clínico completo' },
    { texto: 'Recordatorios automáticos' },
    { texto: 'Soporte técnico incluido' },
  ];

  complementosPlanIndividual: ComplementoPlan[] = [
    { texto: 'POS Farmacia', precio: 30, tipoIcono: 'farmacia' },
    { texto: 'Chat interno de la clínica', precio: 25, tipoIcono: 'chat-interno' },
    { texto: 'Chat con los pacientes', precio: 20, tipoIcono: 'chat' },
  ];

  caracteristicasClinicaPequena: CaracteristicaPlan[] = [
    { texto: 'Sin anuncios - Experiencia premium', destacada: true },
    { texto: 'Chat Doctor-Paciente' },
    { texto: 'Gestión de inventario' },
    { texto: 'Control de finanzas' },
    { texto: 'Recetas y expedientes' },
    { texto: 'Gestión de agenda' },
    { texto: 'Administración de equipo' },
  ];

  complementosClinicaPequena: ComplementoPlan[] = [
    { texto: 'POS Farmacia', precio: 40, tipoIcono: 'farmacia' },
    { texto: 'Chat interno de la clínica', precio: 35, tipoIcono: 'chat-interno' },
    { texto: 'Chat con los pacientes', precio: 30, tipoIcono: 'chat' },
  ];

  caracteristicasClinicaMediana: CaracteristicaPlan[] = [
    { texto: 'Sin anuncios - Experiencia premium', destacada: true },
    { texto: 'Todo del plan Pequeña' },
    { texto: 'Gestión avanzada de pacientes' },
    { texto: 'Expedientes digitales completos' },
    { texto: 'Búsqueda de clínica en app' },
    { texto: 'Perfil con ubicación (Google Maps)' },
    { texto: 'Sistema de reseñas' },
    { texto: 'Reportes analíticos' },
  ];

  complementosClinicaMediana: ComplementoPlan[] = [
    { texto: 'POS Farmacia', precio: 50, tipoIcono: 'farmacia' },
    { texto: 'Chat interno de la clínica', precio: 45, tipoIcono: 'chat-interno' },
    { texto: 'Chat con los pacientes', precio: 40, tipoIcono: 'chat' },
  ];

  caracteristicasClinicaGrande: CaracteristicaPlan[] = [
    { texto: 'Sin anuncios - Experiencia premium', destacada: true },
    { texto: 'Todo del plan Mediana' },
    { texto: 'Múltiples especialidades' },
    { texto: 'Gestión multi-sede' },
    { texto: 'Servicios destacados en búsqueda' },
    { texto: 'API personalizada' },
    { texto: 'Capacitación del equipo' },
    { texto: 'Soporte prioritario 24/7' },
  ];

  complementosClinicaGrande: ComplementoPlan[] = [
    { texto: 'POS Farmacia', precio: 60, tipoIcono: 'farmacia' },
    { texto: 'Chat interno de la clínica', precio: 55, tipoIcono: 'chat-interno' },
    { texto: 'Chat con los pacientes', precio: 50, tipoIcono: 'chat' },
  ];

  caracteristicasEnterprise: CaracteristicaPlan[] = [
    { texto: 'Sin anuncios - Experiencia premium', destacada: true },
    { texto: 'Configuración 100% personalizada' },
    { texto: 'Integración con sistemas existentes' },
    { texto: 'Infraestructura dedicada' },
    { texto: 'SLA garantizado' },
    { texto: 'Gestor de cuenta dedicado' },
    { texto: 'Desarrollo de funciones a medida' },
    { texto: 'Consultoría estratégica' },
  ];

  complementosEnterprise: ComplementoPlan[] = [
    { texto: 'Todos los complementos incluidos', precio: 0, tipoIcono: 'incluido' },
    { texto: 'Desarrollo personalizado', precio: 0, tipoIcono: 'desarrollo' },
    { texto: 'Soporte 24/7 dedicado', precio: 0, tipoIcono: 'soporte' },
  ];

  alCambiarPlan(plan: TipoPlan | string): void {
    this.planActivo.set(plan as TipoPlan);
  }
}


<section id="planes" class="py-20 md:py-28 px-4 relative overflow-hidden">
  <!-- Background decorative elements - eliminados en móvil -->
  <div class="absolute inset-0 overflow-hidden pointer-events-none hidden md:block">
    <div class="absolute top-0 left-1/3 w-96 h-96 bg-[#5a5c8c] rounded-full blur-[120px] opacity-10 dark:opacity-20"></div>
    <div class="absolute bottom-0 right-1/3 w-[500px] h-[500px] bg-[#9ca0c7] rounded-full blur-[140px] opacity-10 dark:opacity-20"></div>
  </div>

  <div class="max-w-7xl mx-auto relative z-10">
    <!-- Section Header -->
    <div 
      appAnimateOnScroll
      class="text-center mb-16 animate-on-scroll">
      <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gradient-to-r from-[#5a5c8c]/10 via-[#9ca0c7]/10 to-[#5a5c8c]/10 dark:from-[#9ca0c7]/20 dark:via-[#5a5c8c]/20 dark:to-[#9ca0c7]/20 backdrop-blur-sm border border-[#5a5c8c]/20 dark:border-[#9ca0c7]/30 mb-6">
        <span class="w-2 h-2 rounded-full bg-[#5a5c8c] dark:bg-[#9ca0c7] animate-pulse"></span>
        <span class="text-sm font-medium text-[#5a5c8c] dark:text-[#9ca0c7]">Planes y Precios</span>
      </div>
      <h2 class="text-4xl md:text-5xl lg:text-6xl font-extrabold text-gray-900 dark:text-white mb-6">
        Un plan para cada <span class="bg-gradient-to-r from-[#5a5c8c] via-[#9ca0c7] to-[#5a5c8c] dark:from-[#9ca0c7] dark:via-[#5a5c8c] dark:to-[#9ca0c7] bg-clip-text text-transparent">necesidad</span>
      </h2>
      <p class="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
        Desde médicos independientes hasta grandes centros de salud, tenemos la solución perfecta para ti
      </p>
    </div>

    <!-- Navegación de pestañas -->
    <div 
      appAnimateOnScroll
      class="w-full flex justify-center shrink-0 max-w-md mx-auto mb-12 animate-on-scroll animate-delay-200">
      <app-tab-navigation
        [activeTab]="planActivo()"
        [tabs]="PESTANAS_PLAN"
        (tabChange)="alCambiarPlan($event)"
        [enableUrlSync]="false"
      />
    </div>

    <!-- Planes Individual -->
    @if (planActivo() === 'Individual') {
      <div 
        appAnimateOnScroll
        class="w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-6 items-stretch justify-items-center animate-on-scroll animate-delay-300 max-w-6xl mx-auto">
        <div class="animate-fade-in-up w-full md:w-full h-full" style="animation-delay: 0.3s; opacity: 0; animation-fill-mode: forwards;">
          <app-plan-card
            [titulo]="'Gratis'"
            [subtitulo]="'1 usuario'"
            [precioBase]="0"
            [precioTexto]="'Gratis'"
            [descripcion]="'Comienza sin costo'"
            [caracteristicas]="caracteristicasPlanGratis"
            [complementos]="complementosPlanGratis"
            [textoBoton]="'Comenzar ahora'"
            [botonDeshabilitado]="false"
            [urlRedireccion]="'https://administracion.everymed.online/'"
            [iconoTipo]="'gratis'"
          />
        </div>

        <div class="animate-fade-in-up w-full md:w-full h-full" style="animation-delay: 0.4s; opacity: 0; animation-fill-mode: forwards;">
          <app-plan-card
            [titulo]="'Plan Individual'"
            [subtitulo]="'1 usuario'"
            [precioBase]="125"
            [precioTexto]="'$125.00'"
            [periodo]="'/mes'"
            [descripcion]="'Perfecto para médicos independientes'"
            [caracteristicas]="caracteristicasPlanIndividual"
            [complementos]="complementosPlanIndividual"
            [esPopular]="true"
            [esDestacado]="true"
            [textoBoton]="'Próximamente'"
            [botonDeshabilitado]="true"
            [iconoTipo]="'individual'"
          />
        </div>

        <div class="animate-fade-in-up w-full md:w-full h-full" style="animation-delay: 0.5s; opacity: 0; animation-fill-mode: forwards;">
          <app-plan-card
            [titulo]="'POS'"
            [subtitulo]="'Farmacia'"
            [precioBase]="79"
            [precioTexto]="'$79'"
            [periodo]="'/mes'"
            [descripcion]="'Únicamente el servicio de venta y administración para tu farmacia'"
            [caracteristicas]="caracteristicasPlanPOS"
            [complementos]="complementosPlanPOS"
            [textoBoton]="'Próximamente'"
            [botonDeshabilitado]="true"
            [iconoTipo]="'pos'"
          />
        </div>
      </div>
    }

    <!-- Planes Empresa -->
    @if (planActivo() === 'Empresa') {
      <div 
        appAnimateOnScroll
        class="w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 sm:gap-6 items-stretch animate-on-scroll animate-delay-300">
        <div class="animate-fade-in-up h-full" style="animation-delay: 0.3s; opacity: 0; animation-fill-mode: forwards;">
          <app-plan-card
            [titulo]="'Clínica Pequeña'"
            [subtitulo]="'2 usuarios'"
            [precioBase]="300"
            [precioTexto]="'$300'"
            [periodo]="'/mes'"
            [descripcion]="'Ideal para clínicas en crecimiento'"
            [caracteristicas]="caracteristicasClinicaPequena"
            [complementos]="complementosClinicaPequena"
            [textoBoton]="'Próximamente'"
            [botonDeshabilitado]="true"
            [iconoTipo]="'empresa'"
          />
        </div>

        <div class="animate-fade-in-up h-full" style="animation-delay: 0.4s; opacity: 0; animation-fill-mode: forwards;">
          <app-plan-card
            [titulo]="'Clínica Mediana'"
            [subtitulo]="'3-5 usuarios'"
            [precioBase]="600"
            [precioTexto]="'$600'"
            [periodo]="'/mes'"
            [descripcion]="'Para clínicas establecidas'"
            [caracteristicas]="caracteristicasClinicaMediana"
            [complementos]="complementosClinicaMediana"
            [esPopular]="true"
            [esDestacado]="true"
            [textoBoton]="'Próximamente'"
            [botonDeshabilitado]="true"
            [iconoTipo]="'empresa'"
          />
        </div>

        <div class="animate-fade-in-up h-full" style="animation-delay: 0.5s; opacity: 0; animation-fill-mode: forwards;">
          <app-plan-card
            [titulo]="'Clínica Grande'"
            [subtitulo]="'6-10 usuarios'"
            [precioBase]="1000"
            [precioTexto]="'$1,000'"
            [periodo]="'/mes'"
            [descripcion]="'Para instituciones grandes'"
            [caracteristicas]="caracteristicasClinicaGrande"
            [complementos]="complementosClinicaGrande"
            [textoBoton]="'Próximamente'"
            [botonDeshabilitado]="true"
            [iconoTipo]="'empresa'"
          />
        </div>

        <div class="animate-fade-in-up h-full" style="animation-delay: 0.6s; opacity: 0; animation-fill-mode: forwards;">
          <app-plan-card
            [titulo]="'Enterprise'"
            [subtitulo]="'+10 usuarios'"
            [precioBase]="0"
            [precioTexto]="'Personalizado'"
            [descripcion]="'Solución personalizada'"
            [caracteristicas]="caracteristicasEnterprise"
            [complementos]="complementosEnterprise"
            [textoBoton]="'Contactar Ventas'"
            [botonDeshabilitado]="false"
            [iconoTipo]="'premium'"
          />
        </div>
      </div>
    }

    <!-- Bottom CTA -->
    <div 
      appAnimateOnScroll
      class="mt-16 text-center animate-on-scroll animate-delay-400">
      <div class="inline-block bg-white/60 dark:bg-gray-900/60 md:backdrop-blur-xl rounded-2xl p-6 border border-white/20 dark:border-gray-700/30 shadow-xl">
        <p class="text-lg text-gray-700 dark:text-gray-300 mb-4">
          ¿Necesitas un plan personalizado para tu institución?
        </p>
        <a href="#contacto" class="inline-flex items-center gap-2 text-[#5a5c8c] dark:text-[#9ca0c7] font-semibold hover:gap-3 transition-all group cursor-pointer">
          Contacta con nuestro equipo de ventas
          <span class="group-hover:translate-x-1 transition-transform">→</span>
        </a>
      </div>
    </div>
  </div>
</section>
