// src/components/FAQ.tsx
import React, { useState } from "react";
import { motion } from "motion/react";
import { Plus, Minus } from "lucide-react";

export function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      question: "¿Es EveryMed adecuado para médicos individuales?",
      answer:
        "¡Absolutamente! EveryMed está diseñado para escalar desde médicos independientes hasta grandes centros médicos. Nuestro plan Individual es perfecto para profesionales que trabajan de forma independiente.",
    },
    {
      question: "¿Cómo protegen mis datos de pacientes?",
      answer:
        "Utilizamos encriptación de nivel hospitalario y cumplimos con todos los estándares HIPAA. Tus datos están almacenados en servidores seguros con respaldo continuo y múltiples capas de protección.",
    },
    {
      question: "¿Puedo acceder desde mi móvil o tablet?",
      answer:
        "Sí, EveryMed es completamente responsive y funciona perfectamente en cualquier dispositivo. Puedes acceder desde tu computadora, tablet o smartphone con la misma experiencia de usuario.",
    },
    {
      question: "¿Ofrecen capacitación para mi equipo?",
      answer:
        "Incluimos capacitación personalizada con todos nuestros planes. Nuestro equipo te acompañará en la implementación y se asegurará de que tú y tu equipo dominen la plataforma.",
    },
    {
      question: "¿Puedo migrar mis datos actuales?",
      answer:
        "Sí, ofrecemos migración de datos sin costo adicional. Nuestro equipo técnico te ayudará a transferir toda tu información desde tu sistema actual a EveryMed de forma segura.",
    },
    {
      question: "¿Qué pasa si necesito cancelar mi suscripción?",
      answer:
        "Puedes cancelar en cualquier momento sin penalización. Todos tus datos permanecerán disponibles para exportación durante 90 días después de la cancelación.",
    },
  ];

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="py-16 md:py-24 px-4 bg-background">
      <div className="max-w-4xl mx-auto">
        {/* Section Header */}
        <motion.div
          className="text-center mb-12 md:mb-16"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
        >
          <motion.div
            className="inline-block mb-4"
            initial={{ opacity: 0, scale: 0.8 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2, duration: 0.5 }}
          >
            <span className="bg-accent text-accent-foreground px-4 py-2 rounded-full">
              Preguntas Frecuentes
            </span>
          </motion.div>
          <motion.h2
            className="text-3xl md:text-4xl text-foreground mb-4"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.3, duration: 0.6 }}
          >
            ¿Tienes preguntas? Tenemos respuestas
          </motion.h2>
          <motion.p
            className="text-muted-foreground max-w-2xl mx-auto"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.4, duration: 0.6 }}
          >
            Resolvemos las dudas más comunes sobre EveryMed
          </motion.p>
        </motion.div>

        {/* FAQ Items */}
        <motion.div
          className="space-y-4"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ delay: 0.2, duration: 0.6 }}
        >
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1 * index, duration: 0.5 }}
              className="bg-card border-2 border-border rounded-2xl overflow-hidden hover:border-primary/50 transition-all duration-300"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full px-6 py-5 flex items-center justify-between text-left transition-colors hover:bg-accent/50"
              >
                <span className="text-foreground pr-8">{faq.question}</span>
                <motion.div
                  animate={{ rotate: openIndex === index ? 180 : 0 }}
                  transition={{ duration: 0.3 }}
                  className="flex-shrink-0"
                >
                  {openIndex === index ? (
                    <Minus className="text-primary" size={20} />
                  ) : (
                    <Plus className="text-muted-foreground" size={20} />
                  )}
                </motion.div>
              </button>

              <motion.div
                initial={false}
                animate={{
                  height: openIndex === index ? "auto" : 0,
                  opacity: openIndex === index ? 1 : 0,
                }}
                transition={{ duration: 0.3, ease: "easeInOut" }}
                className="overflow-hidden"
              >
                <div className="px-6 pb-5 text-muted-foreground">
                  {faq.answer}
                </div>
              </motion.div>
            </motion.div>
          ))}
        </motion.div>

        {/* Additional Help */}
        <motion.div
          className="mt-12 text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.6, duration: 0.6 }}
        >
          <p className="text-muted-foreground mb-4">
            ¿No encuentras lo que buscas?
          </p>
          <motion.button
            className="text-primary hover:underline inline-flex items-center gap-2"
            whileHover={{ x: 5 }}
            transition={{ duration: 0.2 }}
          >
            Contáctanos directamente →
          </motion.button>
        </motion.div>
      </div>
    </section>
  );
}

// src/app/components/faq/faq.component.ts
import { Component, ChangeDetectionStrategy, signal } from '@angular/core';
import { AnimateOnScrollDirective } from '../../directives/animate-on-scroll.directive';
import { CommonModule } from '@angular/common';

interface FAQ {
  question: string;
  answer: string;
}

@Component({
  selector: 'app-faq',
  standalone: true,
  imports: [AnimateOnScrollDirective, CommonModule],
  templateUrl: './faq.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FAQComponent {
  openIndex = signal<number | null>(0);

  faqs: FAQ[] = [
    {
      question: '¿Es EveryMed adecuado para médicos individuales?',
      answer: '¡Absolutamente! EveryMed está diseñado para escalar desde médicos independientes hasta grandes centros médicos. Nuestro plan Individual es perfecto para profesionales que trabajan de forma independiente.'
    },
    {
      question: '¿Cómo protegen mis datos de pacientes?',
      answer: 'Utilizamos encriptación de nivel hospitalario y cumplimos con todos los estándares HIPAA. Tus datos están almacenados en servidores seguros con respaldo continuo y múltiples capas de protección.'
    },
    {
      question: '¿Puedo acceder desde mi móvil o tablet?',
      answer: 'Sí, EveryMed es completamente responsive y funciona perfectamente en cualquier dispositivo. Puedes acceder desde tu computadora, tablet o smartphone con la misma experiencia de usuario.'
    },
    {
      question: '¿Ofrecen capacitación para mi equipo?',
      answer: 'Incluimos capacitación personalizada con todos nuestros planes. Nuestro equipo te acompañará en la implementación y se asegurará de que tú y tu equipo dominen la plataforma.'
    },
    {
      question: '¿Puedo migrar mis datos actuales?',
      answer: 'Sí, ofrecemos migración de datos sin costo adicional. Nuestro equipo técnico te ayudará a transferir toda tu información desde tu sistema actual a EveryMed de forma segura.'
    },
    {
      question: '¿Qué pasa si necesito cancelar mi suscripción?',
      answer: 'Puedes cancelar en cualquier momento sin penalización. Todos tus datos permanecerán disponibles para exportación durante 90 días después de la cancelación.'
    }
  ];

  toggleFAQ(index: number): void {
    this.openIndex.set(this.openIndex() === index ? null : index);
  }
}


<section class="py-20 md:py-28 px-4 relative overflow-hidden">
  <!-- Background decorative elements -->
  <div class="absolute inset-0 overflow-hidden pointer-events-none">
    <div class="absolute top-0 left-1/3 w-96 h-96 bg-[#5a5c8c] rounded-full blur-[120px] opacity-10 dark:opacity-20"></div>
    <div class="absolute bottom-0 right-1/3 w-[500px] h-[500px] bg-[#9ca0c7] rounded-full blur-[140px] opacity-10 dark:opacity-20"></div>
  </div>

  <div class="max-w-4xl mx-auto relative z-10">
    <div 
      appAnimateOnScroll
      class="text-center mb-16 animate-on-scroll">
      <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gradient-to-r from-[#5a5c8c]/10 via-[#9ca0c7]/10 to-[#5a5c8c]/10 dark:from-[#9ca0c7]/20 dark:via-[#5a5c8c]/20 dark:to-[#9ca0c7]/20 backdrop-blur-sm border border-[#5a5c8c]/20 dark:border-[#9ca0c7]/30 mb-6">
        <span class="w-2 h-2 rounded-full bg-[#5a5c8c] dark:bg-[#9ca0c7] animate-pulse"></span>
        <span class="text-sm font-medium text-[#5a5c8c] dark:text-[#9ca0c7]">Preguntas Frecuentes</span>
      </div>
      <h2 class="text-4xl md:text-5xl lg:text-6xl font-extrabold text-gray-900 dark:text-white mb-6">
        ¿Tienes <span class="bg-gradient-to-r from-[#5a5c8c] via-[#9ca0c7] to-[#5a5c8c] dark:from-[#9ca0c7] dark:via-[#5a5c8c] dark:to-[#9ca0c7] bg-clip-text text-transparent">preguntas</span>? Tenemos respuestas
      </h2>
      <p class="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
        Resolvemos las dudas más comunes sobre EveryMed
      </p>
    </div>

    <div 
      appAnimateOnScroll
      class="space-y-4 animate-on-scroll animate-delay-200">
      @for (faq of faqs; track faq.question; let i = $index) {
        <div class="group bg-white/60 dark:bg-gray-900/60 backdrop-blur-xl border-2 border-white/20 dark:border-gray-700/30 rounded-3xl overflow-hidden hover:border-[#5a5c8c]/50 dark:hover:border-[#9ca0c7]/50 transition-all duration-300 shadow-lg hover:shadow-xl">
          <button
            (click)="toggleFAQ(i)"
            class="w-full px-8 py-6 flex items-center justify-between text-left transition-colors hover:bg-gradient-to-r hover:from-[#5a5c8c]/5 hover:to-[#9ca0c7]/5 dark:hover:from-[#9ca0c7]/10 dark:hover:to-[#5a5c8c]/10 cursor-pointer">
            <span class="text-lg text-gray-900 dark:text-white pr-8 font-semibold">{{ faq.question }}</span>
            <span class="flex-shrink-0 w-10 h-10 rounded-full bg-gradient-to-br from-[#5a5c8c]/10 to-[#9ca0c7]/10 dark:from-[#9ca0c7]/20 dark:to-[#5a5c8c]/20 flex items-center justify-center text-[#5a5c8c] dark:text-[#9ca0c7] transition-transform duration-300" [class.rotate-45]="openIndex() === i">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24" [attr.stroke-linecap]="openIndex() === i ? 'round' : 'round'">
                @if (openIndex() === i) {
                  <line x1="5" y1="12" x2="19" y2="12" />
                } @else {
                  <line x1="12" y1="5" x2="12" y2="19" />
                  <line x1="5" y1="12" x2="19" y2="12" />
                }
              </svg>
            </span>
          </button>

          @if (openIndex() === i) {
            <div class="px-8 pb-6 text-gray-600 dark:text-gray-300 leading-relaxed text-lg">
              {{ faq.answer }}
            </div>
          }
        </div>
      }
    </div>

    <div 
      appAnimateOnScroll
      class="mt-16 text-center animate-on-scroll animate-delay-400">
      <div class="inline-block bg-white/60 dark:bg-gray-900/60 backdrop-blur-xl rounded-2xl p-6 border border-white/20 dark:border-gray-700/30 shadow-xl">
        <p class="text-lg text-gray-700 dark:text-gray-300 mb-4">
          ¿No encuentras lo que buscas?
        </p>
        <a href="#contacto" class="inline-flex items-center gap-2 text-[#5a5c8c] dark:text-[#9ca0c7] font-semibold hover:gap-3 transition-all group cursor-pointer">
          Contáctanos directamente
          <span class="group-hover:translate-x-1 transition-transform">→</span>
        </a>
      </div>
    </div>
  </div>
</section>
