// src/components/Testimonials.tsx
import React from "react";
import { Star } from "lucide-react";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { motion } from "motion/react";

export function Testimonials() {
  const testimonials = [
    {
      name: "Dr. José Martínez",
      role: "Médico Individual",
      image:
        "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&h=200&fit=crop",
      rating: 5,
      text: "Como médico independiente, EveryMed me permite gestionar mi consultorio de forma profesional sin necesidad de un equipo técnico.",
    },
    {
      name: "Dra. Laura Fernández",
      role: "Directora - Clínica San Rafael",
      image:
        "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&h=200&fit=crop",
      rating: 5,
      text: "Perfecto para nuestra clínica de 8 médicos. La coordinación entre especialistas y la gestión de pacientes es ahora muy simple.",
    },
    {
      name: "Dr. Roberto Silva",
      role: "CTO - Centro Médico Central",
      image:
        "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop",
      rating: 5,
      text: "Gestionamos 3 sedes con más de 50 profesionales. EveryMed escala perfectamente con nuestras necesidades empresariales.",
    },
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
      },
    },
  };

  const cardVariants = {
    hidden: { opacity: 0, scale: 0.9 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        duration: 0.5,
        ease: "easeOut",
      },
    },
  };

  return (
    <section className="py-16 md:py-24 px-4 bg-muted/50">
      <div className="max-w-7xl mx-auto">
        {/* Section Header */}
        <motion.div
          className="text-center mb-12 md:mb-16"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
        >
          <motion.div
            className="inline-block mb-4"
            initial={{ opacity: 0, scale: 0.8 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2, duration: 0.5 }}
          >
            <span className="bg-card text-foreground px-4 py-2 rounded-full shadow-sm border border-border">
              Testimonios
            </span>
          </motion.div>
          <motion.h2
            className="text-3xl md:text-4xl text-foreground mb-4"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.3, duration: 0.6 }}
          >
            Confianza de profesionales de todos los tamaños
          </motion.h2>
          <motion.p
            className="text-muted-foreground max-w-2xl mx-auto"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.4, duration: 0.6 }}
          >
            Desde médicos individuales hasta grandes centros médicos
          </motion.p>
        </motion.div>

        {/* Testimonials Grid */}
        <motion.div
          className="grid grid-cols-1 md:grid-cols-3 gap-8"
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
        >
          {testimonials.map((testimonial, index) => (
            <motion.div
              key={index}
              variants={cardVariants}
              className="bg-card p-6 rounded-2xl shadow-lg hover:shadow-xl transition-shadow border border-border"
              whileHover={{
                y: -8,
                transition: { duration: 0.3 },
              }}
            >
              {/* Rating */}
              <div className="flex gap-1 mb-4">
                {[...Array(testimonial.rating)].map((_, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, scale: 0 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    transition={{ delay: 0.5 + i * 0.1, duration: 0.3 }}
                  >
                    <Star size={16} className="fill-primary text-primary" />
                  </motion.div>
                ))}
              </div>

              {/* Text */}
              <p className="text-foreground mb-6">"{testimonial.text}"</p>

              {/* Author */}
              <div className="flex items-center gap-3">
                <ImageWithFallback
                  src={testimonial.image}
                  alt={testimonial.name}
                  className="w-12 h-12 rounded-full object-cover"
                />
                <div>
                  <div className="text-foreground">{testimonial.name}</div>
                  <div className="text-sm text-muted-foreground">
                    {testimonial.role}
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}

// src/app/components/testimonials/testimonials.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { AnimateOnScrollDirective } from '../../directives/animate-on-scroll.directive';

@Component({
  selector: 'app-testimonials',
  standalone: true,
  imports: [AnimateOnScrollDirective],
  templateUrl: './testimonials.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TestimonialsComponent {
  testimonials = [
    {
      name: 'Dr. José Martínez',
      role: 'Médico Individual',
      rating: 5,
      text: 'Como médico independiente, EveryMed me permite gestionar mi consultorio de forma profesional sin necesidad de un equipo técnico.'
    },
    {
      name: 'Dra. Laura Fernández',
      role: 'Directora - Clínica San Rafael',
      rating: 5,
      text: 'Perfecto para nuestra clínica de 8 médicos. La coordinación entre especialistas y la gestión de pacientes es ahora muy simple.'
    },
    {
      name: 'Dr. Roberto Silva',
      role: 'CTO - Centro Médico Central',
      rating: 5,
      text: 'Gestionamos 3 sedes con más de 50 profesionales. EveryMed escala perfectamente con nuestras necesidades empresariales.'
    }
  ];
}


<section class="py-20 md:py-28 px-4 relative overflow-hidden">
  <!-- Background decorative elements - eliminados en móvil -->
  <div class="absolute inset-0 overflow-hidden pointer-events-none hidden md:block">
    <div class="absolute top-1/4 right-1/4 w-96 h-96 bg-[#9ca0c7] rounded-full blur-[120px] opacity-10 dark:opacity-20"></div>
    <div class="absolute bottom-1/4 left-1/4 w-[500px] h-[500px] bg-[#5a5c8c] rounded-full blur-[140px] opacity-10 dark:opacity-20"></div>
  </div>

  <div class="max-w-7xl mx-auto relative z-10">
    <div 
      appAnimateOnScroll
      class="text-center mb-16 animate-on-scroll">
      <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gradient-to-r from-[#5a5c8c]/10 via-[#9ca0c7]/10 to-[#5a5c8c]/10 dark:from-[#9ca0c7]/20 dark:via-[#5a5c8c]/20 dark:to-[#9ca0c7]/20 backdrop-blur-sm border border-[#5a5c8c]/20 dark:border-[#9ca0c7]/30 mb-6">
        <span class="w-2 h-2 rounded-full bg-[#5a5c8c] dark:bg-[#9ca0c7] animate-pulse"></span>
        <span class="text-sm font-medium text-[#5a5c8c] dark:text-[#9ca0c7]">Testimonios</span>
      </div>
      <h2 class="text-4xl md:text-5xl lg:text-6xl font-extrabold text-gray-900 dark:text-white mb-6">
        Confianza de <span class="bg-gradient-to-r from-[#5a5c8c] via-[#9ca0c7] to-[#5a5c8c] dark:from-[#9ca0c7] dark:via-[#5a5c8c] dark:to-[#9ca0c7] bg-clip-text text-transparent">profesionales</span> de todos los tamaños
      </h2>
      <p class="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
        Desde médicos individuales hasta grandes centros médicos
      </p>
    </div>

    <div 
      appAnimateOnScroll
      class="grid grid-cols-1 md:grid-cols-3 gap-8 animate-on-scroll animate-delay-200">
      @for (testimonial of testimonials; track testimonial.name) {
        <div class="group relative bg-white/60 dark:bg-gray-900/60 md:backdrop-blur-xl p-8 rounded-3xl shadow-xl md:hover:shadow-2xl transition-all duration-300 border border-white/20 dark:border-gray-700/30 overflow-hidden">
          <!-- Gradient overlay on hover -->
          <div class="absolute inset-0 bg-gradient-to-br from-[#5a5c8c]/5 via-[#9ca0c7]/5 to-[#5a5c8c]/5 dark:from-[#9ca0c7]/10 dark:via-[#5a5c8c]/10 dark:to-[#9ca0c7]/10 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
          
          <div class="relative z-10">
            <!-- Rating -->
            <div class="flex gap-1 mb-6">
              @for (i of [1,2,3,4,5]; track i) {
                <span class="text-2xl text-[#5a5c8c] dark:text-[#9ca0c7]">★</span>
              }
            </div>

            <!-- Text -->
            <p class="text-lg text-gray-900 dark:text-white mb-8 leading-relaxed">"{{ testimonial.text }}"</p>

            <!-- Author -->
            <div class="flex items-center gap-4">
              <div class="w-14 h-14 rounded-full bg-gradient-to-br from-[#5a5c8c] to-[#9ca0c7] flex items-center justify-center text-white font-bold text-lg shadow-lg group-hover:scale-110 transition-transform duration-300">
                {{ testimonial.name.charAt(0) }}
              </div>
              <div>
                <div class="text-gray-900 dark:text-white font-bold text-lg">{{ testimonial.name }}</div>
                <div class="text-sm text-gray-600 dark:text-gray-300">{{ testimonial.role }}</div>
              </div>
            </div>
          </div>
          
          <!-- Decorative corner element -->
          <div class="absolute top-0 right-0 w-24 h-24 bg-gradient-to-br from-[#5a5c8c]/10 to-transparent rounded-bl-full opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
        </div>
      }
    </div>
  </div>
</section>
